feat/#5: week2 xml 과제 구현
NOW-SOPT-ANDROID/youjin-park pull request #7
Opened 2024-04-19 10:23 UTC by youjin09222

## Related issue 🛠
- closed #5 

## Work Description ✏️
- 바텀 네비게이션 연동
- Multi-View Type RecyclerView 사용

## Screenshot 📸
<video src="https://github.com/NOW-SOPT-ANDROID/youjin-park/assets/68536115/f0d6bfed-a4a8-403d-b0e0-82986aa05e9e" width="360"/>

## To Reviewers 📢
-

2024-04-20 01:35 UTC, chattymin requested changes
아니아니아니 왤케 잘하시는거죠?
성장속도 말 안되네요

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private var userData: UserData? = null
data를 저장하는 새로운 방식을 2차 세미나때 배웠어요!!
ViewModel에 저장하고 사용해봅시다!

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +    private var userData: UserData? = null
ViewModel을 사용했을 떄의 장점을 찾아보는것도 좋을것 같아요~

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
>              signUpLauncher.launch(intent) // ActivityResultLauncher 실행
Intent를 사용할 때 Scope를 사용하면 불필요한 변수 생성을 막고, 직관적으로 코드를 작성할 수 있어요. 수정합시다!

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +                }
"userData"라는 String값을 매번 타이핑 하다보면 휴먼에러가 발생할 가능성이 높습니다! 또한 한곳에서만 수정하면 다른곳도 따로 수정해줘야 하기때문에 너무너무 불편해져요! 

한곳에서 저장하고 다른곳에서 호출해서 사용하는 방법으로 바꿔봅시다!

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/LoginActivity.kt
> +        userData?.let { userData ->
let을 적용해본건 너무너무 좋아요!!
하지만, [단점](https://tourspace.tistory.com/208)도 알고 사용하면 좋겠죠??
무조건 수정해라는건 아닙니다! 사용해도 좋지만, 단점을 알고 사용해야 더 좋은 코드를 작성할 수 있어요!

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +        val isValidName = userData.userName.trim().isEmpty() // 공백으로만 이루어진 경우 판단
`isEmpty`와 `isBlank`의 차이점을 찾아보는 것도 좋을 것 같아요~

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/test/data/UserData.kt
> +): Parcelable
크 너무 좋습니다!!

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/test/friend/Friend.kt
> +    }
오 이렇게 미리 매핑해두는 방법 너무 좋은거같아요!! 
저도 하나 배워갑니다 :)

2024-04-20 01:35 UTC, chattymin commented on app/src/main/java/com/sopt/now/test/friend/FriendAdapter.kt
> +        }
너무 좋은 코드 같습니다!!
exception를 던진다면 받는곳에서 처리를 해준다면 더 완벽할 것 같네요!

2024-04-20 16:01 UTC, hyeumm approved these changes
너무 잘해요...부럽다...

2024-04-20 16:01 UTC, hyeeum commented on app/src/main/java/com/sopt/now/test/data/UserData.kt
> +@Parcelize
이런 방법도 있군요..! 하나 배워갑니닷!

2024-04-20 16:01 UTC, hyeumm commented on app/src/main/res/layout/activity_login.xml
오 확실히 전보다 가독성이 좋네요!!

2024-04-21 02:49 UTC, boiledEgg-s approved these changes
너무 많이 발전해서 깜짝 놀랐어요!! 3조는 잘하는 사람들만 모아놨어😖

2024-04-21 02:49 UTC, boiledEgg-s commented on app/src/main/java/com/sopt/now/MainActivity.kt
> +                            arguments = Bundle().apply {
오~ 프래그먼트 간 데이터 전달 방법 중 이런 것도 있군요,, 
번들을 사용하면 좋은 점이 있나요?

2024-05-01 08:54 UTC, chattymin approved these changes
열심히 수정하신 코드가 잘 보입니다!! 고생하셨어요:)
제가 코멘트 수정해서 올려주세용~

2024-05-01 08:54 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +        viewModel = ViewModelProvider(this, factory)[UserViewModel::class.java]
viewModel을 선언할 때 by viewModels()를 활용해봅시다!! 다른분들 코드 보면 있을거에용

2024-05-01 08:54 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +        intent.putExtra("userData", userData)
scope 활용해봅시다!

2024-05-01 08:54 UTC, chattymin commented on app/src/main/java/com/sopt/now/SignUpActivity.kt
> +        showToast(message)
이친구는 setOnClickListener밖에있는 이유가 있을까용?

2024-05-02 06:04 UTC, chattymin approved these changes
굿굿!! 최곱니당~~ 넘나리 열심히 하셨네요!!
이제는 다음주 과제도 열시미 해봅시다!

2024-05-02 15:21 UTC, merged