feat/#6: week2 compose 과제 구현
NOW-SOPT-ANDROID/youjin-park pull request #8
Opened 2024-04-19 14:41 UTC by youjin09222

## Related issue 🛠
- closed #5 

## Work Description ✏️
- 바텀 네비게이션 연동
- Multi-View Type RecyclerView 사용

## Screenshot 📸
<video src="https://github.com/NOW-SOPT-ANDROID/youjin-park/assets/68536115/f0d6bfed-a4a8-403d-b0e0-82986aa05e9e" width="360"/>

## To Reviewers 📢
-

2024-04-20 01:43 UTC, chattymin requested changes
이제 Compose로 UI를 짜는 방법은 정말 잘하는거 같아요!!
xml과제에서 적용하신 디테일들이 조금 빠져있는데 채워넣어도 조을것 같아욤 ㅎㅎ

2024-04-20 01:43 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +            keyboardOptions = if (label == "비밀번호") KeyboardOptions(keyboardType = KeyboardType.Password) else KeyboardOptions.Default
이렇게 String값에 따라 좌우되는 변수는 좋지 못한 방식입니다!
string값이 추후 변경되거나, 다른 타입이 들어온다면 모든 코드가 수정되어야합니다.

이런 값들을 전부 매개변수로 받는 방식으로 바꾸는걸 추천드립니다

2024-04-20 01:43 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +fun LoginCompose(userId: String, userPw: String, userName: String, userDescription: String) {
상태...호이스팅.....
어떤 멋진 OB가 인천공항에서 미미나 해줬더라구요...
적용해볼까요...? 나... 열시미 가르쳤는데....
왜... 상태가.... 최하단에....있을까요....
ㅠ..ㅠㅠㅠ....ㅠㅠㅠㅠㅠㅠㅠㅠ..ㅠㅠㅠㅠ...
이건 못참아 수정하세욧!

2024-04-20 01:43 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +fun ScaffoldExample(userId: String, userPw: String, userName: String, userDescription: String) {
공부하시고 그대로 쓰셨나봐요 ㅎㅎㅎ
네이밍은 누가봐도 이해할 수 있게!

2024-04-20 01:43 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        )
오옹 여기선 야무지게 적용했네요!! 맘에 듭니다 ㅎㅎ

2024-04-20 15:53 UTC, hyeumm approved these changes
역시...GOD유진..

2024-04-20 15:53 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/HomeView.kt
> +                FriendItem(profile)
저는 유저/친구 리스트를 구분해서 만들었는데 이런식으로 인덱스를 활용하는 방법도 있군요! 배워갑니다...!!

2024-04-20 15:53 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +        ScaffoldExample("Id1234", "Password123", "UserName", "INFJ 입니다!")
전 ISFJ인데 히히

2024-04-20 15:53 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/item/FriendItem.kt
> +}
maxLines만 설정하면 이름이나 설명이 긴 경우에 뚝 끊기더라구요..! 말줄임표도 사용해보는건 어떨까요!?

2024-04-20 15:53 UTC, hyeumm commented on app/src/main/java/com/sopt/now/compose/item/UserItem.kt
> +    }
요기도 말줄임표가 있으면 좋을 것 같아요!

2024-04-21 03:00 UTC, boiledEgg-s approved these changes
깔끔하네요!! 역시 다들 기본기가 있어서 실력이 금방금방 느시네~

2024-04-21 03:00 UTC, boiledeggg commented on app/src/main/java/com/sopt/now/compose/HomeView.kt
> +    ),
홈뷰를 호출할 때 사용자 데이터를 받아오지 않는 것 같은데, 고정된 값을 쓰는 건가요? 

만약 그렇다면 로그인한 사용자의 정보를 표시할 수 있도록 수정해야 할 것 같아요!!

2024-05-02 16:05 UTC, chattymin approved these changes
코드 야무지네요!! 죠씁니담 👍

2024-05-02 16:05 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +}
저어는 버튼 클릭했을때나 id,pw바꾸는 것들도 호이스팅 하긴 합니당~

2024-05-02 16:05 UTC, chattymin commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +}
컴포저블 함수는 UI만 담자! 라는게 제 생각이긴 합니당

2024-05-03 10:31 UTC, merged